### ISSUE TITLE
Question 1 - Handled by Swastika

### ISSUE THREAD

**Issue by Swastikamohapatra** [Swastikamohapatra/Probability-Statistics-Assignments#1]
I was able to solve till the third part but I'm facing difficulty from the fourth part onwards. In part 4, I'm not able to obtain a unique value of r. In part 5, I think it cannot be distributed as a poisson random variable because the mean and variance are different.

**Comment by Arvind2903** [comment]
Yes, you seem to be correct, I too faced the same difficulties as above. One fix I can think of is we can solve just using either of the moments, mean or variance. Or we can try both the cases and see in which case the other moment is closer to the expected value.

**Comment by Swastikamohapatra** [comment]
Let's use the mean in both cases. they seem to be a better fit than using the variance.
