### ISSUE TITLE
Question 5 - Handled by Swastika

### ISSUE THREAD

**Issue by Swastikamohapatra** [Swastikamohapatra/Probability-Statistics-Assignments#2]
What exactly is "plug in estimator" in method of moments?

**Comment by Arvind2903** [comment]
Plug in refers to the method by we which we estimate functions of parameters. Say we have to estimate $g(\theta)$, where $g$ is a function on $\mathbb{R}$, then the M-O-M estimate is given by $g(\hat{\theta})$, where $\hat{\theta}$ is the M-O-M estimate of $\theta$. In some sense, we are "plugging in" the value of $\theta$ in $g$.

**Comment by Swastikamohapatra** [comment]
The method of moments assumptions are $E[\epsilon]=0, E[X{\epsilon}]=0$ and $Var[\epsilon]=\sigma^2$. Using that I got that $\hat{\beta} = \frac{Cov(X,Y)}{Var(X)}$ and $\hat{\alpha} = E[Y] - \hat{\beta}E[X]$. We can use the plug in method to solve for $\sigma$.

**Comment by Arvind2903** [comment]
Yes absolutely. In the end, make sure that the parameters tally with the output from `lm`

**Comment by Swastikamohapatra** [comment]
Yes they do.
