### ISSUE TITLE
Question 2 - Handled by Arvind

### ISSUE THREAD

**Issue by Arvind2903** [Swastikamohapatra/Probability-Statistics-Assignments#3]
When we choose the initial point in `optim`, do we take (1.5,2.2) as given or start from somewhere earlier and hope it converges?

**Comment by Swastikamohapatra** [comment]
I don't think it would make much of a difference, since we are sampling from the distribution and re-estimating its parameters. Why don't you try both and see which works best?

**Comment by Arvind2903** [comment]
Okay I did so, and as you had said, both seem to be within the ballpark. I'll stick to an initial guess of (1,2).
