### ISSUE TITLE
Question 3 - Handled by Arvind

### ISSUE THREAD

**Issue by Arvind2903** [Swastikamohapatra/Probability-Statistics-Assignments#4]
I was able to obtain the best estimates in all the three scenarios, and their AIC values don't seem to differ by much. Lognormal seems to be the best fit for the data.

**Comment by Swastikamohapatra** [comment]
Why don't you add a density plot over the histogram? It would look neat and visually depict your best pdf.

**Comment by Arvind2903** [comment]
That seems like a good idea, I'll do it

**Comment by Swastikamohapatra** [comment]
How did you choose your initial point in `optim`?

**Comment by Arvind2903** [comment]
The points seem to clutter at (0,0), so I guessed the intercept to start from 0. We see a point close to (1000,100), so I guessed the slope to start from 0.1, and I arbitrarily chose $\sigma$ to start from 10. I ran multiple guesses for $\sigma$, all of them seem to provide the same answer.

**Comment by Swastikamohapatra** [comment]
Okay, that sounds good. Did you add the density curve?

**Comment by Arvind2903** [comment]
Yes I had and I've reflected the change in my forked repository. I'll send a pull request once we've discussed all questions.

**Comment by Swastikamohapatra** [comment]
Okay great!
