### ISSUE TITLE
Question 4 - Handled by Arvind and Swastika

### ISSUE THREAD

**Issue by Arvind2903** [Swastikamohapatra/Probability-Statistics-Assignments#5]
I am unable to solve for Lognormal and Gamma. The first 2 cases work well and I get some optimal parameters. The regression line seems to be a close fit too. But I'm getting an error : `Unable to evaluate fn at intial points` in parts 3 and 4. I'll include the plots too and send a pull request so you can see what's happening.

**Comment by Swastikamohapatra** [comment]
Okay sure, I'll give it a look.

**Comment by Swastikamohapatra** [comment]
The support of log normal is $(0,\infty)$. I observed that in the data there is one point where `Claims` takes value 0. Maybe we should try removing it and optimizing.

**Comment by Arvind2903** [comment]
Yes that was a great argument and it worked, I'm getting some parameters as an output. I thought of a way to verify it as well. Since `Claims` is lognormal, `log(Claims)`  would be normally distributed. We can cross check our parameters using the ones obtained from `lm(logClaims)~Holders)`, since Gauss Markov conditions for this model is the same as the model we have.

**Comment by Swastikamohapatra** [comment]
Yes that's a great suggestion and the parameters matched, we seem to have the correct parameters! I have another suggestion, let's plot the regression line as well over the scatter plot. Along with the BIC comparison, we can also show the fit of the line

**Comment by Arvind2903** [comment]
Okay I've incorporated those changes and sent a pull request!

**Comment by Swastikamohapatra** [comment]
Done!
